### ISSUE TITLE
Component error: bessarabov - Integration 'bessarabov' not found.

### ISSUE THREAD

**Issue by sshalyminov** [bessarabov/bessarabov_custom_component#2]
Component error: bessarabov - Integration 'bessarabov' not found.
После апгрейда на 2021.6.0
Переустановка не влияет
Интеграция умерла?

**Comment by bessarabov** [comment]
Проще прощения за эту проблему. Я не поправил вовремя код. Сегодня я зарелизил версию 1.1.0 где эта проблема устранена.

Единственное изменение — это файл manifest.json. https://github.com/bessarabov/bessarabov_custom_component/blob/c547376f21f1e3cc031e76f333be99b874154a3f/custom_components/bessarabov/manifest.json Достаточно только его поправить.
